force-app/main/default/objects/Program_Generator_Settings__c/Program_Generator_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Default settings for Program Generator batch processing</description>
    <label>Program Generator Settings</label>
</CustomObject>

force-app/main/default/objects/Program_Generator_Settings__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <description>The default batch size</description>
    <inlineHelpText>The default batch size</inlineHelpText>
    <label>Batch Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProgramGeneratorSettings.cls
public inherited sharing class ProgramGeneratorSettings {
    private static ProgramGeneratorSettings instance;

    public Program_Generator_Settings__c settings { get; private set; }

    private ProgramGeneratorSettings() {
        settings = getSettings();
    }

    public static ProgramGeneratorSettings getInstance() {
        if (ProgramGeneratorSettings.instance == null) {
            ProgramGeneratorSettings.instance = new ProgramGeneratorSettings();
        }
        return ProgramGeneratorSettings.instance;
    }

    private Program_Generator_Settings__c getSettings() {
        List<Program_Generator_Settings__c> settings = [
            SELECT Batch_Size__c
              FROM Program_Generator_Settings__c
             LIMIT 1
        ];

        if (settings.isEmpty()) {
            throw new ProgramGeneratorException('Program Generator Settings not found');
        }

        return settings[0];
    }
    
}