force-app/main/default/objects/Staged_Program__c/Staged_Program__c.object-meta.xml
<CustomObject>
    <description>Represents the variable details needed for an individual program offering in Traction Rec</description>
    <label>Staged Program</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Staged Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staged Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staged_Program__c/fields/Course_Option__c.field-meta.xml
<CustomField>
    <fullName>Course_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Option</label>
    <referenceTo>TREX1__Course_Option__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Staged_Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Staged_Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staged Program Batch</label>
    <referenceTo>Staged_Program_Batch__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Staged</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staged_Program_Batch__c/Staged_Program_Batch__c.object-meta.xml
<CustomObject>
    <description>Represents a collection of staged programs</description>
    <label>Staged Program Batch</label>
    <nameField>
        <displayFormat>SPB-{00000}</displayFormat>
        <label>Staged Program Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staged Program Batches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Staged_Program_Batch__c/fields/Batch_Completed_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Batch_Completed_Date_Time__c</fullName>
    <label>Batch Completed Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Staged_Program_Batch__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <label>Error Log</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Staged_Program_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Staged</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed with Errors</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Batch In Progress</fullName>
                <isActive>false</isActive>
                <label>Batch In Progress</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <isActive>false</isActive>
                <label>Failed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProgramGeneratorBatch.cls
public without sharing class ProgramGeneratorBatch implements Database.Batchable<sObject>, Database.Stateful {

    private static final String BATCH_NAME = 'Program Generator Batch';
    private static final String STATUS_STAGED = 'Staged';
    private static final String STATUS_COMPLETE = 'Complete';
    private static final String STATUS_PROCESSING = 'Processing';
    private static final String STATUS_PROCESSED = 'Processed';
    private static final String STATUS_FAILED = 'Processed with Errors';

    private static String query = 'SELECT Id FROM Staged_Program__c WHERE Staged_Program_Batch__c = :stagedProgramBatchId AND Status__c = :STATUS_STAGED';

    private Id stagedProgramBatchId;
    private Boolean isProcessing = false;
    private List<TREX1__Course_Option__c> courseOptions;
    private List<String> errorMessages = new List<String>();

    public ProgramGeneratorBatch(Id stagedProgramBatchId) {
        this.stagedProgramBatchId = stagedProgramBatchId;
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Staged_Program__c> lstStagedPrograms) {
        if (!this.isProcessing) {
            update (new Staged_Program_Batch__c(Id = this.stagedProgramBatchId, Status__c = STATUS_PROCESSING));
            this.isProcessing = true;
        }

        if (this.courseOptions == null) {
            this.courseOptions = new List<TREX1__Course_Option__c>();
        }

        Set<Id> setStagedProgramIds = new Set<Id>();
        for (Staged_Program__c sp : lstStagedPrograms) {
            setStagedProgramIds.add(sp.Id);
        }

        ProgramGeneratorService service = new ProgramGeneratorService(setStagedProgramIds);
        try {
            List<TREX1__Course_Option__c> lstOptions = service.run();
            this.courseOptions.addAll(lstOptions);
        } catch (Exception e) {
            errorMessages.add('Error Type: ' + e.getTypeName() + '. ' + e.getCause() + ': ' + e.getMessage());
            /*
            Staged_Program_Batch__c spBatch = new Staged_Program_Batch__c();
            spBatch.Id = this.stagedProgramBatchId;
            spBatch.Status__c = STATUS_FAILED;
            spBatch.Error_Log__c = e.getMessage();
            Database.update(spBatch, AccessLevel.SYSTEM_MODE);
            */
        }
    }

    public void finish(Database.BatchableContext bc) {
        Staged_Program_Batch__c batch = [
            SELECT Id, Status__c, Batch_Completed_Date_Time__c, 
                   (SELECT Id FROM Staged_Programs__r WHERE Status__c != :STATUS_PROCESSED)
              FROM Staged_Program_Batch__c
             WHERE Id = :stagedProgramBatchId
             LIMIT 1
        ];

        if (batch.Staged_Programs__r.isEmpty()) {
            batch.Status__c = STATUS_COMPLETE;
            batch.Batch_Completed_Date_Time__c = System.now();
            Database.update(batch, AccessLevel.SYSTEM_MODE);
        }

        if (!Test.isRunningTest() && !this.courseOptions.isEmpty()) {
            TRecCourseOptionBookingBatch bookingBatch = new TRecCourseOptionBookingBatch(
                this.courseOptions,
                this.stagedProgramBatchId
            );
            Database.executeBatch(bookingBatch, 50);
        }

        AsyncApexJob apexJob = BatchUtilities.getAsyncApexJobById(bc.getJobId());
        BatchUtilities.sendJobCreatorEmailResult(apexJob);
    }

}