force-app/main/default/objects/Staged_Program__c/Staged_Program__c.object-meta.xml
<CustomObject>
    <description>Represents the variable details needed for an individual program offering in Traction Rec</description>
    <label>Staged Program</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Staged Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staged Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staged_Program__c/fields/Anonymous_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Anonymous_Ticket__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, the created course option will be an anonymous ticket course option</description>
    <inlineHelpText>If checked, the created course option will be an anonymous ticket course option</inlineHelpText>
    <label>Anonymous Ticket</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Available_Online__c.field-meta.xml
<CustomField>
    <fullName>Available_Online__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, the program will be available for registration online</description>
    <inlineHelpText>If checked, the program will be available for registration online</inlineHelpText>
    <label>Available Online</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>TREX1__Course__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <label>Course Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Course_Option_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Option_Code__c</fullName>
    <label>Course Option Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Course_Option_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Option_Name__c</fullName>
    <label>Course Option Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Course_Session_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Session_Name__c</fullName>
    <label>Course Session Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Days_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Days_of_Week__c</fullName>
    <label>Days of Week</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Exception_Dates__c.field-meta.xml
<CustomField>
    <fullName>Exception_Dates__c</fullName>
    <description>A semi-colon separated list of dates (M/d/yyyy)</description>
    <inlineHelpText>A semi-colon separated list of dates (M/d/yyyy)</inlineHelpText>
    <label>Exception Dates</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/GL_Account__c.field-meta.xml
<CustomField>
    <fullName>GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <referenceTo>TREX1__GL_Account__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/GL_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Number__c</fullName>
    <label>GL Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Has_Member_Price__c.field-meta.xml
<CustomField>
    <fullName>Has_Member_Price__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, a member price level will be generated for the course option product</description>
    <inlineHelpText>If checked, a member price level will be generated for the course option product</inlineHelpText>
    <label>Has Member Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>TREX1__Location__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Location_Name__c.field-meta.xml
<CustomField>
    <fullName>Location_Name__c</fullName>
    <label>Location Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Maximum_Age__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Age__c</fullName>
    <label>Maximum Age</label>
    <precision>12</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Minimum_Age__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Age__c</fullName>
    <label>Minimum Age</label>
    <precision>12</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Primary_Facility__c.field-meta.xml
<CustomField>
    <fullName>Primary_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Facility</label>
    <referenceTo>TREX1__Facility__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Primary_Facility_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Facility_Name__c</fullName>
    <label>Primary Facility Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>TREX1__Program__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <label>Program Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Public_Price__c.field-meta.xml
<CustomField>
    <fullName>Public_Price__c</fullName>
    <label>Public Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>TREX1__Session__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Session_Name__c.field-meta.xml
<CustomField>
    <fullName>Session_Name__c</fullName>
    <label>Session Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Source_Course_Session_Option__c.field-meta.xml
<CustomField>
    <fullName>Source_Course_Session_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If created during an import of past programs, the course session option that this staged program was created from</description>
    <inlineHelpText>If created during an import of past programs, the course session option that this staged program was created from</inlineHelpText>
    <label>Source Course Session Option</label>
    <referenceTo>TREX1__Course_Session_Option__c</referenceTo>
    <relationshipLabel>Generated Staged Programs</relationshipLabel>
    <relationshipName>Generated_Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Staged_Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Staged_Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staged Program Batch</label>
    <referenceTo>Staged_Program_Batch__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Staged</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staged_Program_Batch__c/Staged_Program_Batch__c.object-meta.xml
<CustomObject>
    <description>Represents a collection of staged programs</description>
    <label>Staged Program Batch</label>
    <nameField>
        <displayFormat>SPB-{00000}</displayFormat>
        <label>Staged Program Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staged Program Batches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Staged_Program_Batch__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Session</label>
    <referenceTo>TREX1__Session__c</referenceTo>
    <relationshipLabel>Staged Program Batches</relationshipLabel>
    <relationshipName>Staged_Program_Batches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Staged</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed with Errors</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Batch In Progress</fullName>
                <isActive>false</isActive>
                <label>Batch In Progress</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <isActive>false</isActive>
                <label>Failed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProgramGeneratorCloner.cls
/****************************************************
 * @date 2024
 ****************************************************/
public with sharing class ProgramGeneratorCloner {

    private static final String STATUS_DRAFT = 'Draft';
    private static final String PRICE_TYPE_MEMBER = 'Member';
    private static final Integer QUERY_LIMIT = 10000;

    private Map<Id, TREX1__Price_Level__c> productIdToPriceLevelMap;

    private Id batchId;
    private Id originalSessionId;
    private Id targetSessionId;
    private List<TREX1__Course_Session_Option__c> courseSessionOptions;
    private Integer daysToAdd;

    private TREX1__Session__c originalSession;
    private TREX1__Session__c targetSession;

    public ProgramGeneratorCloner(FlowProgramGeneratorCloner.Request request) {
        this(
            request.batchId,
            request.originalSessionId,
            request.targetSessionId,
            new Set<Id>(request.courseSessionOptionIds)
        );
        this.setDaysToAdd(request.daysToAdd);
    }

    public ProgramGeneratorCloner(
        Id batchId, 
        Id originalSessionId, 
        Id targetSessionId,
        Set<Id> courseSessionOptionIds
    ) {
        this.batchId = batchId;
        this.courseSessionOptions = queryForCourseSessionOptions(courseSessionOptionIds);
        this.originalSessionId = originalSessionId;
        this.targetSessionId = targetSessionId;
        this.setSessions();
    }

    public void setDaysToAdd(Integer daysToAdd) {
        this.daysToAdd = daysToAdd;
    }

    private void setSessions() {
        for (TREX1__Session__c session : [SELECT Id, Name, Session_Code__c
                                            FROM TREX1__Session__c
                                           WHERE Id IN (:this.originalSessionId, :this.targetSessionId)
                                            WITH USER_MODE
                                           LIMIT 2]) 
        {
            if (session.Id == this.originalSessionId) {
                this.originalSession = session;
            }
            if (session.Id == this.targetSessionId) {
                this.targetSession = session;
            }
        }
    }

    public List<Staged_Program__c> createStagedPrograms() {
        return insertStagedPrograms( createStagedProgramsFromCSOs() );
    }

    private List<Staged_Program__c> createStagedProgramsFromCSOs() {
        List<Staged_Program__c> stagedPrograms = new List<Staged_Program__c>();
        for (TREX1__Course_Session_Option__c cso : courseSessionOptions) {
            stagedPrograms.add( createStagedProgramFromCSO(cso) );
        }
        return stagedPrograms;
    }

    private Staged_Program__c createStagedProgramFromCSO(TREX1__Course_Session_Option__c cso) {
        Staged_Program__c stagedProgram = new Staged_Program__c();
        stagedProgram.Staged_Program_Batch__c = this.batchId;
        stagedProgram.Status__c = STATUS_DRAFT;
        stagedProgram.Source_Course_Session_Option__c = cso.Id;
        stagedProgram.Program__c = cso.TREX1__cso_Course_Session__r.TREX1__Course__r.TREX1__Program__c;
        stagedProgram.Program_Name__c = cso.TREX1__cso_Course_Session__r.TREX1__Course__r.TREX1__Program__r.Name;
        stagedProgram.Course_Name__c = cso.TREX1__cso_Course_Session__r.TREX1__Course__r.Name;
        stagedProgram.Course__c = cso.TREX1__cso_Course_Session__r.TREX1__Course__c;
        stagedProgram.Session__c = targetSessionId;
        stagedProgram.Session_Name__c = cso.TREX1__cso_Course_Session__r.TREX1__Session__r.Name;
        stagedProgram.Course_Session_Name__c = replaceSessionInfo(cso.TREX1__cso_Course_Session__r.Name);
        stagedProgram.Course_Option_Name__c = replaceSessionInfo(cso.TREX1__Course_Option__r.Name);
        stagedProgram.Days_of_Week__c = cso.TREX1__Course_Option__r.TREX1__Day_of_Week__c;
        stagedProgram.Start_Date__c = cso.TREX1__Course_Option__r.TREX1__Start_Date__c.addDays(this.daysToAdd);
        stagedProgram.End_Date__c = cso.TREX1__Course_Option__r.TREX1__End_Date__c.addDays(this.daysToAdd);
        stagedProgram.Start_Time__c = cso.TREX1__Course_Option__r.TREX1__Start_Time__c;
        stagedProgram.End_Time__c = cso.TREX1__Course_Option__r.TREX1__End_Time__c;
        stagedProgram.Location__c = cso.TREX1__Course_Option__r.TREX1__Location__c;
        stagedProgram.Location_Name__c = cso.TREX1__Course_Option__r.TREX1__Location__r.Name;
        if (cso.TREX1__Course_Option__r.Primary_Facility__c != null) {
            stagedProgram.Primary_Facility__c = cso.TREX1__Course_Option__r.Primary_Facility__c;
            stagedProgram.Primary_Facility_Name__c = cso.TREX1__Course_Option__r.Primary_Facility__r.Name;
        }
        stagedProgram.Minimum_Age__c = cso.TREX1__Course_Option__r.TREX1__Age_Min__c;
        stagedProgram.Maximum_Age__c = cso.TREX1__Course_Option__r.TREX1__Age_Max__c;
        stagedProgram.Capacity__c = cso.TREX1__Course_Option__r.TREX1__Capacity__c;
        stagedProgram.Anonymous_Ticket__c = cso.TREX1__Course_Option__r.TREX1__Unnamed_Group_Registration__c;
        stagedProgram.Available_Online__c = true;

        // Pricing
        TREX1__Price_Level__c priceLevel = getPriceLevelMap().get(cso.TREX1__Course_Option__r.TREX1__Product__c);
        if (priceLevel != null) {
            stagedProgram.Public_Price__c = priceLevel.TREX1__Total_Billing_Schedule_Amount__c;
            stagedProgram.Has_Member_Price__c = true;
            stagedProgram.GL_Account_Number__c = priceLevel.TREX1__GL_Account_Recurring_Fee_Primary__r.TREX1__GL_Account_Number__c;
            stagedProgram.GL_Account__c = priceLevel.TREX1__GL_Account_Recurring_Fee_Primary__c;    
        }

        stagedProgram.Course_Option_Code__c = replaceSessionInfo(cso.TREX1__Course_Option__r.TREX1__Code__c);

        return stagedProgram;
    }

    private String replaceSessionInfo(String originalString) {
        String result = '';
        if (!String.isBlank(originalString)) {
            result = originalString.replaceAll(originalSession.Session_Code__c, targetSession.Session_Code__c).replaceAll(originalSession.Name, targetSession.Name);
        }
        return result;
    }

    private List<Staged_Program__c> insertStagedPrograms(List<Staged_Program__c> stagedPrograms) {
        Database.insert(stagedPrograms, AccessLevel.USER_MODE);
        return stagedPrograms;
    }

    private Map<Id, TREX1__Price_Level__c> getPriceLevelMap() {
        if (productIdToPriceLevelMap == null) {
            productIdToPriceLevelMap = new Map<Id, TREX1__Price_Level__c>();
            for (TREX1__Price_Level__c priceLevel : queryForPriceLevels()) {
                productIdToPriceLevelMap.put(priceLevel.TREX1__Product__c, priceLevel);
            }
        }
        return productIdToPriceLevelMap;
    }

    private List<TREX1__Price_Level__c> queryForPriceLevels() {
        Set<Id> productIds = getProductIds();
        return [
            SELECT Id, 
                   TREX1__Product__c, 
                   TREX1__Total_Billing_Schedule_Amount__c, 
                   TREX1__GL_Account_Recurring_Fee_Primary__c, 
                   TREX1__GL_Account_Recurring_Fee_Primary__r.TREX1__GL_Account_Number__c
              FROM TREX1__Price_Level__c
             WHERE TREX1__Product__c IN :productIds
               AND TREX1__Price_Type__c != :PRICE_TYPE_MEMBER
              WITH USER_MODE
             LIMIT :QUERY_LIMIT
        ];
    }

    private Set<Id> getProductIds() {
        Set<Id> productIds = new Set<Id>();
        for (TREX1__Course_Session_Option__c cso : courseSessionOptions) {
            productIds.add(cso.TREX1__Course_Option__r.TREX1__Product__c);
        }
        return productIds;
    }

    private List<TREX1__Course_Session_Option__c> queryForCourseSessionOptions(Set<Id> courseSessionOptionIds) {
        return [
            SELECT Id, 
                   TREX1__Course_Option__c, 
                   TREX1__Course_Option__r.Name, 
                   TREX1__Course_Option__r.TREX1__Code__c, 
                   TREX1__Course_Option__r.TREX1__Start_Date__c,
                   TREX1__Course_Option__r.TREX1__End_Date__c,
                   TREX1__Course_Option__r.TREX1__Day_of_Week__c,
                   TREX1__Course_Option__r.TREX1__Start_Time__c,
                   TREX1__Course_Option__r.TREX1__End_Time__c,
                   TREX1__Course_Option__r.TREX1__Location__c,
                   TREX1__Course_Option__r.TREX1__Location__r.Name,
                   TREX1__Course_Option__r.Exception_Dates__c,
                   TREX1__Course_Option__r.TREX1__Age_Min__c,
                   TREX1__Course_Option__r.TREX1__Age_Max__c,
                   TREX1__Course_Option__r.TREX1__Capacity__c,
                   TREX1__Course_Option__r.Primary_Facility__c,
                   TREX1__Course_Option__r.Primary_Facility__r.Name,
                   TREX1__Course_Option__r.TREX1__Product__c,
                   TREX1__Course_Option__r.TREX1__Unnamed_Group_Registration__c, 
                   TREX1__cso_Course_Session__c, 
                   TREX1__cso_Course_Session__r.Name, 
                   TREX1__cso_Course_Session__r.TREX1__Session__c, 
                   TREX1__cso_Course_Session__r.TREX1__Session__r.Name,
                   TREX1__cso_Course_Session__r.TREX1__Course__c,
                   TREX1__cso_Course_Session__r.TREX1__Course__r.Name,
                   TREX1__cso_Course_Session__r.TREX1__Course__r.TREX1__Program__r.Name
              FROM TREX1__Course_Session_Option__c
             WHERE Id IN :courseSessionOptionIds
              WITH USER_MODE
             LIMIT :QUERY_LIMIT
        ];
    }

}