force-app/main/default/objects/Staged_Program__c/Staged_Program__c.object-meta.xml
<CustomObject>
    <description>Represents the variable details needed for an individual program offering in Traction Rec</description>
    <label>Staged Program</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Staged Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staged Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staged_Program__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>TREX1__Session__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Staged_Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Staged_Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staged Program Batch</label>
    <referenceTo>Staged_Program_Batch__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program_Batch__c/Staged_Program_Batch__c.object-meta.xml
<CustomObject>
    <description>Represents a collection of staged programs</description>
    <label>Staged Program Batch</label>
    <nameField>
        <displayFormat>SPB-{00000}</displayFormat>
        <label>Staged Program Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staged Program Batches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Staged_Program_Batch__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Session</label>
    <referenceTo>TREX1__Session__c</referenceTo>
    <relationshipLabel>Staged Program Batches</relationshipLabel>
    <relationshipName>Staged_Program_Batches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FlowProgramGeneratorCloner_Test.cls
@IsTest
private class FlowProgramGeneratorCloner_Test {

    @TestSetup
    static void makeData() {
        TREX1__Program__c program = TestDataFactory.createTractionRecProgramLibrary();
        TREX1__Session__c session = [SELECT Id, Name FROM TREX1__Session__c LIMIT 1];
        Staged_Program_Batch__c batch = TestDataFactory.createStagedProgramBatches(session, 1).get(0);
        insert batch;
        List<Staged_Program__c> stagedPrograms = TestDataFactory.createStagedPrograms(batch, program, 5);
        insert stagedPrograms;
    }
    
    @IsTest
    static void testCloner() {
        Staged_Program_Batch__c batch = [SELECT Id, Session__c FROM Staged_Program_Batch__c LIMIT 1];
        List<Id> courseSessionOptionIds = new List<Id>();
        List<TREX1__Course_Session_Option__c> csos = [
            SELECT Id
              FROM TREX1__Course_Session_Option__c
             WHERE TREX1__cso_Course_Session__r.TREX1__Session__c = :batch.Session__c
        ];
        for (TREX1__Course_Session_Option__c cso : csos) {
            courseSessionOptionIds.add(cso.Id);
        }

        List<FlowProgramGeneratorCloner.Result> results;
        Test.startTest();
        FlowProgramGeneratorCloner.Request request = new FlowProgramGeneratorCloner.Request();
        request.batchId = batch.Id;
        request.originalSessionId = batch.Session__c;
        request.targetSessionId = batch.Session__c;
        request.courseSessionOptionIds = courseSessionOptionIds;
        request.daysToAdd = 10;

        results = FlowProgramGeneratorCloner.createStagedPrograms(
            new List<FlowProgramGeneratorCloner.Request>{ request }
        );
        Test.stopTest();

        Assert.areEqual(
            csos.size(), 
            results[0].stagedPrograms.size(),
            'Should have received a staged program for each original record'
        );
    }
    
}