force-app/main/default/objects/Staged_Program__c/Staged_Program__c.object-meta.xml
<CustomObject>
    <description>Represents the variable details needed for an individual program offering in Traction Rec</description>
    <label>Staged Program</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Staged Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staged Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staged_Program__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>TREX1__Course__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Course_Option__c.field-meta.xml
<CustomField>
    <fullName>Course_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Option</label>
    <referenceTo>TREX1__Course_Option__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Course_Option_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Option_Code__c</fullName>
    <label>Course Option Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Course_Option_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Option_Name__c</fullName>
    <label>Course Option Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Course_Session__c.field-meta.xml
<CustomField>
    <fullName>Course_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Session</label>
    <referenceTo>TREX1__Course_Session__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Course_Session_Key__c.field-meta.xml
<CustomField>
    <fullName>Course_Session_Key__c</fullName>
    <formula>Course_Session_Name__c &amp; &quot;-&quot; &amp; CASESAFEID( Course__c ) &amp; &quot;-&quot; &amp; CASESAFEID( Session__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Session Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Course_Session_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Session_Name__c</fullName>
    <label>Course Session Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Days_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Days_of_Week__c</fullName>
    <label>Days of Week</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Exception_Dates__c.field-meta.xml
<CustomField>
    <fullName>Exception_Dates__c</fullName>
    <description>A semi-colon separated list of dates (M/d/yyyy)</description>
    <inlineHelpText>A semi-colon separated list of dates (M/d/yyyy)</inlineHelpText>
    <label>Exception Dates</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/GL_Account__c.field-meta.xml
<CustomField>
    <fullName>GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <referenceTo>TREX1__GL_Account__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Has_Member_Price__c.field-meta.xml
<CustomField>
    <fullName>Has_Member_Price__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, a member price level will be generated for the course option product</description>
    <inlineHelpText>If checked, a member price level will be generated for the course option product</inlineHelpText>
    <label>Has Member Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>TREX1__Location__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Maximum_Age__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Age__c</fullName>
    <label>Maximum Age</label>
    <precision>12</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Member_Price__c.field-meta.xml
<CustomField>
    <fullName>Member_Price__c</fullName>
    <description>15% of public price</description>
    <formula>IF( Has_Member_Price__c, (Public_Price__c * 0.85), Public_Price__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>15% of public price</inlineHelpText>
    <label>Member Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Minimum_Age__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Age__c</fullName>
    <label>Minimum Age</label>
    <precision>12</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Minimum_Participants__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Participants__c</fullName>
    <label>Minimum Participants</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Price_Level_Key__c.field-meta.xml
<CustomField>
    <fullName>Price_Level_Key__c</fullName>
    <formula>&quot;Public-&quot; &amp; TEXT( Public_Price__c ) &amp; &quot;-&quot; &amp; GL_Account__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price Level Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Primary_Facility__c.field-meta.xml
<CustomField>
    <fullName>Primary_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Facility</label>
    <referenceTo>TREX1__Facility__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>TREX1__Program__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Public_Price__c.field-meta.xml
<CustomField>
    <fullName>Public_Price__c</fullName>
    <label>Public Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>TREX1__Session__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Staged</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TREX1__Course_Session__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <formula>Name &amp; &quot;-&quot; &amp; CASESAFEID( TREX1__Course__c ) &amp; &quot;-&quot; &amp; CASESAFEID( TREX1__Session__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TREX1__Session__c/fields/BPC_Free_Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>BPC_Free_Membership_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BPC Free Membership Type</label>
    <referenceTo>TREX1__Membership_Type__c</referenceTo>
    <relationshipLabel>Sessions (BPC)</relationshipLabel>
    <relationshipName>BPC_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TREX1__Session__c/fields/UES_Free_Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>UES_Free_Membership_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UES Free Membership Type</label>
    <referenceTo>TREX1__Membership_Type__c</referenceTo>
    <relationshipLabel>Sessions (UES)</relationshipLabel>
    <relationshipName>UES_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProgramGeneratorService.cls
public with sharing class ProgramGeneratorService {

    private List<Staged_Program__c> stagedPrograms;
    private Map<Id, TREX1__Session__c> mapSessions;
    private Map<String, TREX1__Course_Session__c> mapCourseSessions = new Map<String, TREX1__Course_Session__c>();

    public ProgramGeneratorService(Set<Id> stagedProgramIds) {
        this.stagedPrograms = queryForStagedPrograms(stagedProgramIds);
    }

    /**
     * @description Main entry point for processing staged programs.
     * Processes staged programs provided in constructor
     * @returns void
     */
    public void run() {
        // Add pre-existing course sessions to map
        Map<String, TREX1__Course_Session__c> mapCourseSessions = getCourseSessionMap();

    }

    private Map<String, TREX1__Course_Session__c> getCourseSessionMap() {
        // Get existing course sessions from course session keys
        Map<String, Staged_Program__c> mapCsKeyToStagedProgram = new Map<String, Staged_Program__c>();
        for (Staged_Program__c sp : stagedPrograms) {
            mapCsKeyToStagedProgram.put(sp.Course_Session_Key__c, sp);
        }
        for (TREX1__Course_Session__c cs : queryForCourseSessions(mapCsKeyToStagedProgram.keySet())) {
            mapCourseSessions.put(cs.Name, cs);
        }

        // Create new course sessions for remaining course session keys
        List<Staged_Program__c> lstSpsWithNewCs = new List<Staged_Program__c>();
        for (String csKey : mapCsKeyToStagedProgram.keySet()) {
            if (!mapCourseSessions.containsKey(csKey)) {
                lstSpsWithNewCs.add(mapCsKeyToStagedProgram.get(csKey));
            }
        }
        for (TREX1__Course_Session__c newCs : createNewCourseSessions(lstSpsWithNewCs)) {
            mapCourseSessions.put(newCs.Name, newCs);
        }

        // Return course session map
        return mapCourseSessions;
    }

    private List<TREX1__Course_Session__c> createNewCourseSessions(
        List<Staged_Program__c> lstStagedPrograms
    ) {
        List<TREX1__Course_Session__c> lstCourseSessions = new List<TREX1__Course_Session__c>();
        for (Staged_Program__c newCsSp : lstStagedPrograms) {
            TREX1__Course_Session__c newCs = new TREX1__Course_Session__c(
                Name = newCsSp.Course_Session_Name__c,
                TREX1__Course__c = newCsSp.Course__c,
                TREX1__Session__c = newCsSp.Session__c
            );
            lstCourseSessions.add(newCs);
        }
        return lstCourseSessions;
    }

    private List<TREX1__Course_Session__c> queryForCourseSessions(
        Set<String> setCourseSessionKeys
    ) {
        return [
            SELECT Id, 
                   Name, 
                   Key__c
              FROM TREX1__Course_Session__c 
             WHERE Key__c IN :setCourseSessionKeys
              WITH USER_MODE
        ];
    }

    private Map<Id, TREX1__Session__c> getSessionMap() {
        if (mapSessions == null) {
            Set<Id> setSessionIds = new Set<Id>();
            for (Staged_Program__c sp : stagedPrograms) {
                setSessionIds.add(sp.Session__c);
            }
            mapSessions = new Map<Id, TREX1__Session__c>([
                SELECT Id,
                       Name,
                       BPC_Free_Membership_Type__c,
                       UES_Free_Membership_Type__c,
                       TREX1__Start_Date__c,
                       TREX1__End_Date__c,
                       TREX1__Register_From_Date__c,
                       TREX1__Register_To_Date__c,
                       TREX1__Register_From_Time__c,
                       TREX1__Register_To_Time__c,
                       TREX1__Register_Online_From_Date__c,
                       TREX1__Register_Online_To_Date__c,
                       TREX1__Register_Online_From_Time__c,
                       TREX1__Register_Online_To_Time__c
                  FROM TREX1__Session__c
                 WHERE Id IN :setSessionIds
            ]);
        }
        return mapSessions;
    }

    private List<Staged_Program__c> queryForStagedPrograms(
        Set<Id> stagedProgramIds
    ) {
        return [
            SELECT Id,
                   Status__c,
                   Error_Message__c,
                   Program__c,
                   Course__c,
                   GL_Account__c,
                   Session__c,
                   Primary_Facility__c,
                   Location__c,
                   Start_Date__c,
                   End_Date__c,
                   Start_Time__c,
                   End_Time__c,
                   Exception_Dates__c,
                   Days_of_Week__c,
                   Capacity__c,
                   Minimum_Participants__c,
                   Minimum_Age__c,
                   Maximum_Age__c,
                   Public_Price__c,
                   Member_Price__c,
                   Has_Member_Price__c,
                   Price_Level_Key__c,
                   Course_Session_Name__c,
                   Course_Session_Key__c,
                   Course_Option_Name__c,
                   Course_Option_Code__c,
                   Course_Session__c,
                   Course_Option__c
              FROM Staged_Program__c
             WHERE Id IN :stagedProgramIds
              WITH USER_MODE
             LIMIT 200
        ];
    }

}