force-app/main/default/objects/Staged_Program__c/Staged_Program__c.object-meta.xml
<CustomObject>
    <description>Represents the variable details needed for an individual program offering in Traction Rec</description>
    <label>Staged Program</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Staged Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staged Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staged_Program__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>TREX1__Course__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Course_Option_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Option_Name__c</fullName>
    <label>Course Option Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Course_Session_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Session_Name__c</fullName>
    <label>Course Session Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>TREX1__Location__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>TREX1__Program__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Staged_Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Staged_Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staged Program Batch</label>
    <referenceTo>Staged_Program_Batch__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Staged</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staged_Program_Batch__c/Staged_Program_Batch__c.object-meta.xml
<CustomObject>
    <description>Represents a collection of staged programs</description>
    <label>Staged Program Batch</label>
    <nameField>
        <displayFormat>SPB-{00000}</displayFormat>
        <label>Staged Program Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staged Program Batches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Staged_Program_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Staged</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed with Errors</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Batch In Progress</fullName>
                <isActive>false</isActive>
                <label>Batch In Progress</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <isActive>false</isActive>
                <label>Failed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StagedProgramEditorController.cls
public with sharing class StagedProgramEditorController {
    
    @AuraEnabled
    public static List<Staged_Program__c> getStagedPrograms(Id recordId) {
        try {
            return [
                SELECT Id, 
                       Status__c, 
                       Location__c, 
                       Program__c, 
                       Course__c, 
                       Course_Session_Name__c, 
                       Course_Option_Name__c
                  FROM Staged_Program__c
                 WHERE Staged_Program_Batch__c = :recordId
                  WITH USER_MODE
                 LIMIT 2000
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=false)
    public static String updateStagedPrograms() {
        try {
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=false)
    public static String deleteStagedPrograms() {
        try {
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}