force-app/main/default/objects/Staged_Program__c/Staged_Program__c.object-meta.xml
<CustomObject>
    <description>Represents the variable details needed for an individual program offering in Traction Rec</description>
    <label>Staged Program</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Staged Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staged Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staged_Program__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>TREX1__Location__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>TREX1__Session__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Staged_Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Staged_Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staged Program Batch</label>
    <referenceTo>Staged_Program_Batch__c</referenceTo>
    <relationshipLabel>Staged Programs</relationshipLabel>
    <relationshipName>Staged_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Staged</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staged_Program_Batch__c/Staged_Program_Batch__c.object-meta.xml
<CustomObject>
    <description>Represents a collection of staged programs</description>
    <label>Staged Program Batch</label>
    <nameField>
        <displayFormat>SPB-{00000}</displayFormat>
        <label>Staged Program Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staged Program Batches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Staged_Program_Batch__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Session</label>
    <referenceTo>TREX1__Session__c</referenceTo>
    <relationshipLabel>Staged Program Batches</relationshipLabel>
    <relationshipName>Staged_Program_Batches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staged_Program_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Staged</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed with Errors</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Batch In Progress</fullName>
                <isActive>false</isActive>
                <label>Batch In Progress</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <isActive>false</isActive>
                <label>Failed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProgramGeneratorBatch_Test.cls
@IsTest
private class ProgramGeneratorBatch_Test {

    private static final Integer NUM_COURSE_OPTIONS = 10;

    @TestSetup
    static void makeData() {
        TREX1__Program__c program = TestDataFactory.createTractionRecProgramLibrary();
        TREX1__Session__c session = [SELECT Id, Name FROM TREX1__Session__c LIMIT 1];
        Staged_Program_Batch__c batch = TestDataFactory.createStagedProgramBatches(session, 1).get(0);
        insert batch;
        List<Staged_Program__c> stagedPrograms = TestDataFactory.createStagedPrograms(
            batch, 
            program, 
            NUM_COURSE_OPTIONS
        );
        insert stagedPrograms;
    }

    @IsTest
    static void testBatch() {
        Id stagedProgramBatchId = [SELECT Id FROM Staged_Program_Batch__c LIMIT 1].Id;
        
        Test.startTest();
        ProgramGeneratorBatch pgb = new ProgramGeneratorBatch(stagedProgramBatchId);
        Id batchId = Database.executeBatch(pgb, 20);
        Test.stopTest();

        List<TREX1__Course_Option__c> lstCos = [
            SELECT Id FROM TREX1__Course_Option__c WHERE Staged_Program_Batch__c = :stagedProgramBatchId
        ];
        
        Assert.areEqual(
            NUM_COURSE_OPTIONS, 
            lstCos.size(), 
            'Should have received ' + NUM_COURSE_OPTIONS + ' course options'
        );
    }

    @IsTest
    static void testBatchWithException() {
        TREX1__Program__c program = [SELECT Id FROM TREX1__Program__c LIMIT 1];
        TREX1__Session__c session = TestDataFactory.createSessions(1).get(0);
        insert session;

        Staged_Program_Batch__c spb = TestDataFactory.createStagedProgramBatches(session, 1).get(0);
        insert spb;

        // Create upper east side location to force error when no free membership type is defined
        TREX1__Location__c location = TestDataFactory.createLocations(1).get(0);
        location.Name = 'Upper East Side';
        insert location;

        Staged_Program__c stagedProgram = TestDataFactory.createStagedPrograms(spb, program, 1).get(0);
        stagedProgram.Location__c = location.Id;
        stagedProgram.Session__c = session.Id;
        insert stagedProgram;
        
        Test.startTest();
        ProgramGeneratorBatch pgb = new ProgramGeneratorBatch(spb.Id);
        Id batchId = Database.executeBatch(pgb, 20);
        Test.stopTest();

        Staged_Program_Batch__c refreshedBatch = [SELECT Status__c FROM Staged_Program_Batch__c WHERE Id = :spb.Id LIMIT 1];

        Assert.areEqual('Processed with Errors', refreshedBatch.Status__c, 'Should have received a failed batch status');
    }

}